CREATE TABLE Clients (
  id INT NOT NULL AUTO_INCREMENT,
  fullName VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE,
  phone_number BIGINT UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Client PRIMARY KEY (id)
);

CREATE TABLE Managers (
  id INT NOT NULL AUTO_INCREMENT,
  fullName VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE,
  phone_number BIGINT UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Manager PRIMARY KEY (id)
);

CREATE TABLE Deliverers (
  id INT NOT NULL AUTO_INCREMENT,
  fullName VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE,
  phone_number BIGINT UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Deliverer PRIMARY KEY (id)
);

CREATE TABLE Orders (
  id INT NOT NULL AUTO_INCREMENT,
  clientId INT NOT NULL,
  delivererId INT,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  quantity INT DEFAULT 1,
  pickupLocLongitude DECIMAL,
  pickupLocLatitude DECIMAL,
  dropoffLocLongitude DECIMAL,
  dropoffLocLatitude DECIMAL,
  state ENUM('wait for deliverer', 'on the way', 'submitted'),
  submittedAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Order PRIMARY KEY (id, delivererId),
  CONSTRAINT FK_Order FOREIGN KEY (clientId) REFERENCES Clients(id) ON DELETE CASCADE
);